services:
  backend:
    container_name: scanprice-backend
    image: ${BACKEND_IMAGE}  

    ports:
      - "3000:3000"

    env_file:
      - .env

    restart: unless-stopped

    # Protección contra llenado de disco
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Rota el log cuando llega a 10MB
        max-file: "3"   # Guarda un máximo de 3 archivos