name: Deploy to Amazon S3
run-name: ${{ github.actor }} is deploying out GitHub Actions 🚀
on:
  push:
    branches: [ 'main' ]
    
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-south-2

      - name: Copy Repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          corepack enable pnpm
          pnpm install

      - name: Build
        run: pnpm --filter scanprice-frontend build

      - name: Update S3 bucket
        run: aws s3 sync ./packages/frontend/dist/ ${{ vars.BUCKET_NAME }} --delete

      - name: Invalidate cloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
